# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
#
maxconn = 32
httpchk = "GET /"

[front-end]
listen = "*"
port = 80
mode = "http"

[status]
enabled = false
listen = "*"
port = 9000
user = "admin"
password = "password"
uri = "/haproxy-stats"

