maxconn = 32
httpchk = 'GET /national-parks'

[front-end]
listen = '*'
port = 8085
mode = 'http'

[status]
nabled = true
listen = '*'
port = 8000
user = 'admin'
password = 'password'
uri = '/haproxy-stats'
